### ISSUE TITLE
Calendar Page: Event items

### ISSUE THREAD

**Issue by Chaoward** [SahisN/ACM_Mobile_APP#5]
Make EventCard widget class with...

constructor that accepts an "info: Map class and creates the widget based on the Map provided
clickable to expand and show information

**Comment by SahisN** [comment]
Card should be a sperate class in widget folder (eg. EventItem or EventCard).

**Comment by Chaoward** [comment]
Make EventCard widget class with...

- constructor that accepts an "info: Map class and creates the widget based on the Map provided
- clickable to expand and show information
